language: c
sudo: required
services:
  - docker

matrix:
  include:
    - env:
      - TARGET_OS=linux64
      - DOCKER_IMAGE=multiarch/crossbuild
      - CROSS_TRIPLE=x86_64-linux-gnu
      - BUILD_DIR=/workdir
    - env:
      - TARGET_OS=linux32
      # multiarch/crossbuild doesn't come with 32-bit compilers, use a different image
      - DOCKER_IMAGE=dockcross/linux-x86
      - CROSS_TRIPLE=i686-linux-gnu
      - BUILD_DIR=/work
    - env:
      - TARGET_OS=linux-armhf
      - DOCKER_IMAGE=multiarch/crossbuild
      - CROSS_TRIPLE=arm-linux-gnueabihf
      - BUILD_DIR=/workdir
    - env:
      - TARGET_OS=win32
      - DOCKER_IMAGE=multiarch/crossbuild
      - CROSS_TRIPLE=i686-w64-mingw32
      - BUILD_DIR=/workdir
      # multiarch/crossbuild doesn't come with 'zip',
      # so we build a tgz archive in the container, and re-package it later in the script.
      - EXTRA_ARGS='-e ARCHIVE=tar'
    - env:
      - TARGET_OS=osx
      - DOCKER_IMAGE=multiarch/crossbuild
      - CROSS_TRIPLE=x86_64-apple-darwin
      - BUILD_DIR=/workdir


script:
  - export VER=$(git describe)
  - echo ${VER}

  - >-
    docker run --rm
    -v ${PWD}:${BUILD_DIR}
    -e TARGET_OS=${TARGET_OS}
    -e CROSS_TRIPLE=${CROSS_TRIPLE}
    ${EXTRA_ARGS}
    ${DOCKER_IMAGE}
    make clean dist

  # for windows, prepare zip archive
  - |
    if [ $TARGET_OS = "win32" ]; then
      rm -f esptool-${VER}-win32.tar.gz
      zip -r esptool-${VER}-win32.zip esptool-${VER}-win32/
    fi

  # Diagnostics
  - file esptool-${VER}-${TARGET_OS}/*
  - ls -l esptool-${VER}-${TARGET_OS}/*

  # Prepare a file with size and sha256
  - export DIST_NAME=$(ls -1 esptool-${VER}-${TARGET_OS}.*)
  - DIST_SIZE=$(wc -c <${DIST_NAME} 2>/dev/null | tr -d ' ')
  - DIST_SHA256=$(shasum -a 256 ${DIST_NAME} | cut -d ' ' -f1)
  - echo ${DIST_NAME} ${DIST_SIZE} ${DIST_SHA256} >esptool-${VER}-${TARGET_OS}.sha256.txt 

notifications:
  email:
    recipients:
    - volcas@gmail.com
    on_success: change
    on_failure: change

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: Kpx53rzNK/teMgjL12UVHTLcrI7G3PXN/EkV5Z8eSvmjhnsy5ww0pZvnOYh4VmSqZ5WXqOH0M1ctTkEjOFqSeCx0JJ7B5tfUQdPS8+Tbj8aHaYCXTow9qvDXA4uIEuoFX6NleQgsBSpEG8FIQbxGksFh1E2XjjyyqlhN76esaXwxeRRd8vAgmUXPuz/NnFqbvXY50GRaWW2EL41g2vHwZArM9jWxSNxAIP2/sjP1hdbuEAwJxOHr0EBEtca8C09E/5AN7553W8tkm3ZxAhkC7mx0GODI8RFYy4AI5RZ5pTq3oaQh1xEbEXqz9jBfGVGNWImMIKL2kGCysaHvru1BGehmMwiDWY17rCqdwnYmokbkx60z55rgIened4c5x9SxhtnV6lmSGN7YQ1BUkMIkaCouy/h9HoRO81LXrMbtsUTgU5KLqzUaZQ1DP/Au8Gi5TvIBtPrEWoMhi4Roaae0CqQJvDoMI9bLFppaPT5I+uXPYgmcceTRQ7eG3FNEzt4U5XpcGBsl3wMqjKworRepPYjhc5ldI+x6Ing73RZzrRWQaEUFXenoG3brcy6ghjrkRNHHoaM9iMaw0Z68zre5n6XkHv2pkmAoPoY7eQ7jqvTHBl8gJA1M4q4DdA9xp5yu4Mvy1DYVHpuvX6MX142OEMKjKHDrCsoquxzak2EB/Zw=
  file: esptool-$TRAVIS_TAG-$TARGET_OS.*
  on:
    repo: volca/esptool-ck
    tags: true
